import { GeistSans } from 'geist/font/sans'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={GeistSans.className} style={{ backgroundColor: "var(--Midnight, #000110)" }}>
      <body>{children}</body>
    </html>
  )
}
